spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gateway01ap-southeast-1-prod.aws.tidbcloud.com:4000/halodb?useSSL=true&serverTimezone=Asia/Shanghai&useServerPrepStmts=false&cachePrepStmts=false&dontTrackOpenResources=true&metadataCacheSize=5
    username: "2Ur133XyPKnjGjt.root"
    password: "HMv2wqq9lQ8RUc5M"
  hikari:
    maximum-pool-size: 2
    minimum-idle: 1
halo:
  work-dir: /root/.halo2

